on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - run: |
        mvn --batch-mode --update-snapshots verify
        gh auth login --with-token ${{secrets.GITHUB_TOKEN}}
        gh release create v1.0 target/build.jar
    # - run: cp target/build.jar docs
    - uses: actions/upload-artifact@v2
      with:
         name: Package
         path: target/build.jar
    # - run: |
        # git config --global user.name 'Santiago Ruiz'
        # git config --global user.email 'hiebra@hotmail.com'
        # git add docs/build.jar
        # git commit -am "Automated build"
        # git push
