on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn -Dgithub.user=hiebra -Dgithub.token=${{secrets.GITHUB_TOKEN}} clean deploy
    - name: Release
      run: |
        echo ${{secrets.GITHUB_TOKEN}} > token
        gh auth login --with-token < token
        gh release create "v$(<target/classes/version.txt)" target/build.jar
    - uses: actions/upload-artifact@v2
      with:
         name: Package
         path: target/build.jar
    # - run: |
        # git config --global user.name 'Santiago Ruiz'
        # git config --global user.email 'hiebra@hotmail.com'
        # git add docs/build.jar
        # git commit -am "Automated build"
        # git push
