on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build & package deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn -Dgithub.user=hiebra -Dgithub.token=${{secrets.GITHUB_TOKEN}} deploy
    # - name: Release
    #  run: |
    #    echo ${{secrets.GITHUB_TOKEN}} > token
    #    gh auth login --with-token < token
    #    gh release create "v$(<target/classes/version.txt)" target/build.jar
    - uses: actions/upload-artifact@v2
      with:
         name: jar
         path: target/build.jar
    - name: Display structure of checked out files
      run: ls -R
    # - run: |
        # git config --global user.name 'Santiago Ruiz'
        # git config --global user.email 'hiebra@hotmail.com'
        # git add docs/build.jar
        # git commit -am "Automated build"
        # git push
  deploy:
    name: Main (CLI) deployment
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checking out ebookipedia/exe
      uses: actions/checkout@v2
      with:
          repository: ebookipedia/exe
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Downloading build.jar into ./docs
      uses: actions/download-artifact@v2
      with:
        name: jar
        path: docs
    - name: Display structure of downloaded files
      run: |
        ls -R
        jar tf ./docs/build.jar
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        repository: ebookipedia/exe
        github_token: ${{ secrets.DEPLOYMENT }}
